name: ainotebooks
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.8
  - numpy>=1.24.3
  - matplotlib>=3.7.1
  - scipy>=1.10.1
  - scikit-learn>=1.2.2
  - jupyter>=1.0.0
  - ipykernel>=6.22.0
  - ipywidgets>=8.1.5
  - ipympl>=0.9.7
  - nbstripout>=0.6.1
  - tensorflow==2.10.0
  - sympy==1.13.3



